import {onRequest} from 'firebase-functions/v2/https';
import {initializeApp} from 'firebase-admin/app';import {getAuth} from 'firebase-admin/auth';import {getFirestore} from 'firebase-admin/firestore';
import {positive,borrowStock,returnStock,validateItem} from './domain.js';
initializeApp();const db=getFirestore();
const text=(v,max=100)=>String(v??'').trim().slice(0,max);
const phone=v=>text(v,20).replace(/[() +\-]/g,'');
function id(v){const s=text(v,100);if(!s||s.includes('/'))throw Error('編號格式錯誤');return s}
async function manager(req){const token=(req.headers.authorization||'').replace(/^Bearer /,'');if(!token)throw Error('請先登入');const u=await getAuth().verifyIdToken(token);const email=(u.email||'').toLowerCase();const s=await db.doc('authorizedUsers/'+email).get();if(!s.exists||s.data().enabled!==true)throw Error('尚未開通管理權限');return {email,...s.data()}}
function credential(b){const studentId=text(b.studentId),p=phone(b.phone);if(!studentId||p.length<8)throw Error('請填學號／員編與聯絡手機');return {studentId,phone:p}}
const publicItem=d=>({id:d.id,name:d.name,category:d.category,propertyId:d.propertyId||'',location:d.location||'',available:d.available,borrowed:d.borrowed,total:d.total,note:d.note||'',enabled:d.enabled!==false});
export const inventoryApi=onRequest({region:'asia-east1',cors:['https://f00931must-hash.github.io'],maxInstances:5},async(req,res)=>{try{const route=req.path.replace(/^\//,'');const b=req.body||{};const getRoutes=['items','me','loans'];if(req.method!==(getRoutes.includes(route)?'GET':'POST'))return res.status(405).json({error:'不支援的操作'});
if(route==='items'){const snap=await db.collection('items').get();return res.json(snap.docs.map(d=>publicItem({id:d.id,...d.data()})))}
if(route==='me'){const u=await manager(req);return res.json({name:u.name||u.displayName||u.email})}
if(route==='item'||route==='import'){const u=await manager(req);const rows=route==='item'?[b]:b.items;if(!Array.isArray(rows)||rows.length<1||rows.length>100)throw Error('每次限 1–100 筆');const clean=rows.map(r=>validateItem({...r,id:id(r.id),name:text(r.name,200),category:text(r.category),propertyId:text(r.propertyId),location:text(r.location,200),note:text(r.note,1000)}));if(new Set(clean.map(x=>x.id)).size!==clean.length)throw Error('物品編號重複');await db.runTransaction(async tx=>{const refs=clean.map(x=>db.doc('items/'+x.id));const old=await tx.getAll(...refs);if(old.some(x=>x.exists))throw Error('已有相同編號，不會覆蓋');clean.forEach((x,i)=>tx.create(refs[i],{...x,enabled:true,createdBy:u.email,createdAt:new Date().toISOString()}))});return res.json({ok:true,count:clean.length})}
if(route==='loans'){await manager(req);const s=await db.collection('loans').orderBy('borrowedAt','desc').get();return res.json(s.docs.map(d=>({id:d.id,...d.data()})))}
if(route==='lookup'){const c=credential(b);const s=await db.collection('loans').where('studentId','==',c.studentId).get();return res.json(s.docs.filter(d=>d.data().phone===c.phone&&d.data().remaining>0).map(d=>{const x=d.data();return {id:d.id,itemName:x.itemName,remaining:x.remaining,borrowedAt:x.borrowedAt,dueDate:x.dueDate}}))}
if(route==='borrow'){const c=credential(b),quantity=positive(b.quantity),name=text(b.name),unit=text(b.unit);if(!name||!unit)throw Error('請填姓名與班級／單位');if(!['student','staff'].includes(b.identity))throw Error('身分格式錯誤');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(!/^\d{4}-\d{2}-\d{2}$/.test(b.dueDate)||b.dueDate<today)throw Error('預計歸還日期不可早於今天');const ref=db.doc('items/'+id(b.itemId)),loan=db.doc('loans/'+id(b.requestId));const result=await db.runTransaction(async tx=>{const [s,prior]=await tx.getAll(ref,loan);if(prior.exists){if(prior.data().studentId!==c.studentId||prior.data().phone!==c.phone)throw Error('單號重複');const p=prior.data();return {loanId:loan.id,itemName:p.itemName,quantity:p.quantity,borrowedAt:p.borrowedAt}}if(!s.exists)throw Error('找不到物品');const x=s.data(),next=borrowStock(x,quantity),at=new Date().toISOString();tx.update(ref,next);tx.create(loan,{...c,name,unit,identity:b.identity,itemId:ref.id,itemName:x.name,quantity,remaining:quantity,dueDate:b.dueDate,borrowedAt:at,note:text(b.note,500),returns:[]});return {loanId:loan.id,itemName:x.name,quantity,borrowedAt:at}});return res.json(result)}
if(route==='return'){const c=credential(b),quantity=positive(b.quantity),loan=db.doc('loans/'+id(b.loanId)),op=db.doc('returnOperations/'+id(b.requestId));const result=await db.runTransaction(async tx=>{const [s,prior]=await tx.getAll(loan,op);if(!s.exists||s.data().studentId!==c.studentId||s.data().phone!==c.phone)throw Error('找不到符合的借用紀錄');if(prior.exists){if(prior.data().loanId!==loan.id)throw Error('操作編號重複');return prior.data().result}const l=s.data(),ref=db.doc('items/'+l.itemId),stock=await tx.get(ref);if(!stock.exists)throw Error('找不到物品');const next=returnStock(stock.data(),l,quantity),at=new Date().toISOString(),result={quantity,remaining:next.remaining,returnedAt:at};tx.update(ref,{available:next.available,borrowed:next.borrowed});tx.update(loan,{remaining:next.remaining,returns:[...(l.returns||[]),{quantity,at}],...(next.remaining===0?{returnedAt:at}:{})});tx.create(op,{loanId:loan.id,result});return result});return res.json(result)}
return res.status(404).json({error:'找不到功能'});
}catch(e){console.error(e);res.status(400).json({error:e.message||'操作失敗'})}});
