import {firebaseConfig,apiBase} from './config.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[],user=null,auth=null,sdk=null,page='borrow',adminTab='stock',pendingRows=[];
const ready=Boolean(apiBase&&firebaseConfig);let busy=false;
function notice(s){$('notice').textContent=s;$('notice').style.display='block';setTimeout(()=>$('notice').style.display='none',4500)}
async function api(path,body){if(!ready)throw Error('尚未接上資料庫，目前無法送出');const token=user?await user.getIdToken():null;const r=await fetch(apiBase.replace(/\/$/,'')+'/'+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'連線失敗');return d}
async function action(button,fn){if(busy)return;busy=true;button.disabled=true;try{await fn()}catch(e){notice(e.message)}finally{busy=false;if(button.isConnected)button.disabled=false}}
function field(name,label,type='text',extra=''){return `<label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" required ${extra}>`}
const identity=()=>`<div class="row">${field('studentId','學號／員編','text','autocomplete="off"')}${field('phone','聯絡手機','tel','inputmode="tel" pattern="[0-9+() -]{8,20}" autocomplete="tel"')}</div>`;
function renderBorrow(){const cats=[...new Set(items.map(x=>x.category))].sort();$('page').innerHTML=`<div class="panel"><h1>借用物品</h1><form id="borrowForm"><fieldset ${ready?'':'disabled'}><label for="category">物品分類</label><select id="category" required><option value="">請選擇分類</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select><label for="item">物品名稱</label><select id="item" name="itemId" required><option value="">先選擇分類</option></select><div id="itemInfo"></div><div class="row">${field('quantity','借用數量','number','min="1" step="1" value="1"')}${field('dueDate','預計歸還日期','date',`min="${taipeiDate()}"`)}</div>${field('name','借用人姓名','text','autocomplete="name"')}<label for="identity">身分別</label><select id="identity" name="identity"><option value="student">學生</option><option value="staff">教職員／行政人員</option></select>${field('unit','班級／單位')}${identity()}<label for="note">備註（選填）</label><textarea id="note" name="note" maxlength="500"></textarea><button class="submit">確認借出</button></fieldset></form></div>`;
const fill=()=>{const rows=items.filter(x=>x.category===$('category').value&&x.enabled!==false);$('item').innerHTML='<option value="">請選擇物品</option>'+rows.map(x=>`<option value="${esc(x.id)}" ${x.available===0?'disabled':''}>${esc(x.name)} · 可借 ${x.available} 件</option>`).join('');$('itemInfo').innerHTML=''};
$('category').onchange=fill;$('item').onchange=()=>{const i=items.find(x=>x.id===$('item').value);$('itemInfo').innerHTML=i?`<div class="meta">物品編號：${esc(i.propertyId||i.id)}<br>存放位置：${esc(i.location||'請洽資源教室')}</div>`:'';if(i)$('quantity').max=i.available};
const selected=new URLSearchParams(location.search).get('item');if(selected){const i=items.find(x=>x.id===selected);if(i){$('category').value=i.category;fill();$('item').value=i.id;$('item').onchange()}}
$('borrowForm').onsubmit=e=>{e.preventDefault();action(e.submitter,async()=>{const data=Object.fromEntries(new FormData(e.target));data.requestId=crypto.randomUUID();const r=await api('borrow',data);await loadItems();$('page').innerHTML=`<div class="panel"><h1>借出完成</h1><div class="success">${esc(r.itemName)}，${r.quantity} 件<br>單號：${esc(r.loanId)}<br>借出時間：${fmt(r.borrowedAt)}<br>預計歸還：${esc(data.dueDate)}</div><button id="again" class="submit">繼續借用</button></div>`;$('again').onclick=renderBorrow})}}
function taipeiDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function fmt(s){return s?new Date(s).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'—'}
function renderReturn(){ $('page').innerHTML=`<div class="panel"><h1>歸還物品</h1><form id="lookup"><fieldset ${ready?'':'disabled'}>${identity()}<button class="submit">查詢未歸還物品</button></fieldset></form><div id="loans"></div></div>`;$('lookup').onsubmit=e=>{e.preventDefault();action(e.submitter,async()=>{const credential=Object.fromEntries(new FormData(e.target));const rows=await api('lookup',credential);$('loans').innerHTML=rows.length?rows.map(x=>`<article class="card"><h2>${esc(x.itemName)}</h2><p>借出：${fmt(x.borrowedAt)}</p><p>預計歸還：${esc(x.dueDate)} · 未歸還 ${x.remaining} 件</p><form data-return="${esc(x.id)}"><label for="qty-${esc(x.id)}">本次歸還數量</label><input id="qty-${esc(x.id)}" name="quantity" type="number" min="1" max="${x.remaining}" step="1" value="${x.remaining}" required><button class="submit">確認歸還</button></form></article>`).join(''):'<div class="meta">沒有未歸還的物品。</div>';$('loans').querySelectorAll('form').forEach(f=>f.onsubmit=ev=>{ev.preventDefault();action(ev.submitter,async()=>{const result=await api('return',{...credential,loanId:f.dataset.return,quantity:f.elements.quantity.value,requestId:crypto.randomUUID()});await loadItems();f.closest('.card').innerHTML=`<div class="success">已歸還 ${result.quantity} 件<br>${fmt(result.returnedAt)}${result.remaining?`<br>尚有 ${result.remaining} 件未歸還`:''}</div>`})})})}}
async function loadItems(){items=await api('items')}
function navigate(p){page=p;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='borrow')renderBorrow();else if(p==='return')renderReturn();else renderAdmin()}
async function login(){if(!ready){notice('需先完成新系統 Firebase 設定');return}if(!sdk){const [a,b]=await Promise.all([import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js')]);sdk=b;auth=b.getAuth(a.initializeApp(firebaseConfig));}try{const result=await sdk.signInWithPopup(auth,new sdk.GoogleAuthProvider());user=result.user;await api('me');navigate('admin')}catch(e){user=null;notice(e.message)}}
async function renderAdmin(){if(!user){login();return}$('page').innerHTML=`<div class="admin-panel"><div class="tools"><button data-tab="stock">租借庫存</button><button data-tab="loans">借還紀錄</button><button data-tab="promotion">文宣品庫存</button><button id="logout" class="quiet">登出</button></div><div id="adminContent"></div></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{adminTab=b.dataset.tab;renderAdminContent()});$('logout').onclick=async()=>{await sdk.signOut(auth);user=null;navigate('borrow')};await renderAdminContent()}
async function renderAdminContent(){const box=$('adminContent');if(adminTab==='promotion'){box.innerHTML='<h1>文宣品庫存</h1><p class="muted">文宣品的欄位及領用流程確認後，會在這裡加入。</p>';return}if(adminTab==='loans'){box.innerHTML='<h1>借還紀錄</h1><p>載入中…</p>';try{const rows=await api('loans');box.innerHTML=`<h1>借還紀錄</h1><div class="tools"><button id="exportLoans">匯出借還紀錄</button><select id="loanFilter"><option value="open">未歸還</option><option value="all">全部紀錄</option></select></div><div id="loanTable"></div>`;const show=()=>{$('loanTable').innerHTML=table(['物品','借用人','班級／單位','借出','預計歸還','未歸還','歸還紀錄'],rows.filter(x=>$('loanFilter').value==='all'||x.remaining>0).map(x=>[x.itemName,x.name,x.unit,fmt(x.borrowedAt),x.dueDate,x.remaining,(x.returns||[]).map(r=>`${fmt(r.at)} ${r.quantity}件`).join('；')]))};show();$('loanFilter').onchange=show;$('exportLoans').onclick=()=>xlsx(rows.map(x=>({'單號':x.id,'物品':x.itemName,'姓名':x.name,'學號/員編':x.studentId,'班級/單位':x.unit,'聯絡手機':x.phone,'借出數量':x.quantity,'未歸還':x.remaining,'借出時間':fmt(x.borrowedAt),'預計歸還日期':x.dueDate,'歸還紀錄':(x.returns||[]).map(r=>`${fmt(r.at)} ${r.quantity}件`).join('；')})),'借還紀錄')}catch(e){box.textContent=e.message}return}
box.innerHTML=`<h1>租借庫存</h1><div class="stats"><div class="card">物品種類<strong>${items.length}</strong></div><div class="card">目前借出<strong>${items.reduce((n,x)=>n+x.borrowed,0)}</strong></div></div><div class="tools"><input id="search" placeholder="搜尋物品、編號、位置" aria-label="搜尋物品"><button id="export">匯出 Excel</button><button id="import">匯入 Excel</button></div><input id="file" type="file" accept=".xlsx,.xls,.csv" hidden><div id="importPreview"></div><details><summary>新增物品</summary><form id="newItem">${field('assetId','資產編號')}${field('itemName','物品名稱')}${field('itemCategory','物品分類')}${field('initial','庫存數量','number','min="0" step="1"')}<label for="location">存放位置</label><input id="location" name="location"><label for="propertyId">財產編號（選填）</label><input id="propertyId" name="propertyId"><button class="submit">建立物品</button></form></details><div id="stockTable"></div>`;
const show=()=>{const q=$('search').value.trim().toLowerCase();$('stockTable').innerHTML=table(['資產編號','物品名稱','分類','借出','可借','存放位置'],items.filter(x=>[x.id,x.propertyId,x.name,x.category,x.location].join(' ').toLowerCase().includes(q)).map(x=>[x.id,x.name,x.category,x.borrowed,x.available,x.location]))};show();$('search').oninput=show;$('export').onclick=()=>xlsx(items.map(toExcel),'資產總表');$('import').onclick=()=>$('file').click();$('file').onchange=previewImport;
$('newItem').onsubmit=e=>{e.preventDefault();action(e.submitter,async()=>{const d=Object.fromEntries(new FormData(e.target));await api('item',{id:d.assetId,name:d.itemName,category:d.itemCategory,total:Number(d.initial),borrowed:0,available:Number(d.initial),location:d.location,propertyId:d.propertyId,note:''});await loadItems();await renderAdminContent();notice('物品已建立')})}}
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length?'':'<p class="muted">沒有符合的紀錄。</p>'}</div>`}
function toExcel(x){return {'資產編號':x.id,'財產編號':x.propertyId,'物品大類':x.category,'物品名稱':x.name,'原始庫存數量':x.total,'目前借出數量':x.borrowed,'目前庫存數量':x.available,'庫存狀態':x.available>0?'在庫中':'無庫存','存放位置':x.location,'備註':x.note}}
function xlsx(rows,name){if(!window.XLSX){notice('Excel 功能載入失敗，請重新整理');return}const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(rows),name);XLSX.writeFile(w,name+'.xlsx')}
async function previewImport(e){try{if(!window.XLSX)throw Error('Excel 功能尚未載入');const file=e.target.files[0];if(!file)return;const w=XLSX.read(await file.arrayBuffer(),{type:'array'}),raw=XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:'',raw:false});pendingRows=raw.map(r=>({id:String(r['資產編號']).trim(),propertyId:r['財產編號'],category:r['物品大類'],name:r['物品名稱'],total:Number(r['原始庫存數量']),borrowed:Number(r['目前借出數量']),available:Number(r['目前庫存數量']),location:r['存放位置'],note:r['備註']}));const seen=new Set(),errors=[];pendingRows.forEach((r,i)=>{if(!r.id||!r.name||!r.category||['total','borrowed','available'].some(k=>!Number.isSafeInteger(r[k])||r[k]<0)||r.total!==r.borrowed+r.available||seen.has(r.id)||items.some(x=>x.id===r.id))errors.push(`第 ${i+2} 列 ${r.name||r.id}：資料異常、重複編號或已有物品`);seen.add(r.id)});$('importPreview').innerHTML=`<div class="meta">讀取 ${pendingRows.length} 筆。${errors.length?`<p class="bad">${errors.length} 筆需修正，尚未匯入。</p>${errors.slice(0,12).map(esc).join('<br>')}`:'僅新增物品，不覆蓋既有庫存。'}</div><button id="confirmImport" class="submit" ${errors.length?'disabled':''}>確認新增 ${pendingRows.length} 筆物品</button>`;$('confirmImport').onclick=e=>action(e.target,async()=>{for(let n=0;n<pendingRows.length;n+=100)await api('import',{items:pendingRows.slice(n,n+100)});await loadItems();await renderAdminContent();notice('匯入完成')})}catch(e){notice(e.message)}}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$('adminButton').onclick=()=>navigate('admin');
if(!ready)$('connection').innerHTML='<div class="banner">系統尚未完成資料庫設定，借還與管理功能暫未開放。</div>';else{try{await loadItems()}catch(e){$('connection').innerHTML=`<div class="banner">${esc(e.message)}</div>`}}navigate('borrow');
