import {filterLoans,loanStatus} from './loan-filters.js';
import {firebaseConfig,portalFirebaseConfig,apiBase} from './config.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[],user=null,auth=null,sdk=null,page='borrow',adminTab='stock',pendingRows=[];
const ready=Boolean(apiBase&&firebaseConfig);let busy=false;
function notice(s){$('notice').textContent=s;$('notice').style.display='block';setTimeout(()=>$('notice').style.display='none',4500)}
async function api(path,body){if(!ready)throw Error('尚未接上資料庫，目前無法送出');const token=user?await user.getIdToken():null;const r=await fetch(apiBase.replace(/\/$/,'')+'/'+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'連線失敗');return d}
async function action(button,fn){if(busy)return;busy=true;button.disabled=true;try{await fn()}catch(e){notice(e.message)}finally{busy=false;if(button.isConnected)button.disabled=false}}
function field(name,label,type='text',extra=''){return `<label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" required ${extra}>`}
const identity=()=>`<div class="row">${field('studentId','學號／員編','text','autocomplete="off"')}${field('phone','聯絡手機','tel','inputmode="tel" pattern="[0-9+() -]{8,20}" autocomplete="tel"')}</div>`;
function renderBorrow(){const cats=[...new Set(items.map(x=>x.category))].sort();$('page').innerHTML=`<div class="panel"><h1>借用物品</h1><form id="borrowForm"><fieldset ${ready?'':'disabled'}><label for="category">物品大類</label><select id="category" required><option value="">請選擇大類</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select><label for="item">物品名稱</label><select id="item" name="itemId" required><option value="">先選擇大類</option></select><div id="itemInfo"></div><div class="row">${field('quantity','借用數量','number','min="1" step="1" value="1"')}${field('dueDate','預計歸還日期','date',`min="${taipeiDate()}"`)}</div>${field('name','借用人姓名','text','autocomplete="name"')}<label for="identity">身分別</label><select id="identity" name="identity"><option value="student">學生</option><option value="staff">教職員／行政人員</option></select>${field('unit','班級／單位')}${identity()}<label for="note">備註（選填）</label><textarea id="note" name="note" maxlength="500"></textarea><button class="submit">確認借出</button></fieldset></form></div>`;
const fill=()=>{const rows=items.filter(x=>x.category===$('category').value&&x.enabled!==false);$('item').innerHTML='<option value="">請選擇物品</option>'+rows.map(x=>`<option value="${esc(x.id)}" ${x.available===0?'disabled':''}>${esc(x.name)} · 可借 ${x.available} 件</option>`).join('');$('itemInfo').innerHTML=''};
$('category').onchange=fill;$('item').onchange=()=>{const i=items.find(x=>x.id===$('item').value);$('itemInfo').innerHTML=i?`<div class="meta">物品編號：${esc(i.propertyId||i.id)}<br>存放位置：${esc(i.location||'請洽資源教室')}</div>`:'';if(i)$('quantity').max=i.available};
const selected=new URLSearchParams(location.search).get('item');if(selected){const i=items.find(x=>x.id===selected);if(i){$('category').value=i.category;fill();$('item').value=i.id;$('item').onchange()}}
$('borrowForm').onsubmit=e=>{e.preventDefault();action(e.submitter,async()=>{const data=Object.fromEntries(new FormData(e.target));const payload=JSON.stringify(data);if(e.target.dataset.payload!==payload){e.target.dataset.payload=payload;e.target.dataset.requestId=crypto.randomUUID()}data.requestId=e.target.dataset.requestId;const r=await api('borrow',data);await loadItems().catch(()=>notice('借出已完成，庫存更新稍後重試'));$('page').innerHTML=`<div class="panel"><h1>借出完成</h1><div class="success">${esc(r.itemName)}，${r.quantity} 件<br>單號：${esc(r.loanId)}<br>借出時間：${fmt(r.borrowedAt)}<br>預計歸還：${esc(data.dueDate)}</div><button id="again" class="submit">繼續借用</button></div>`;$('again').onclick=renderBorrow})}}
function taipeiDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function fmt(s){return s?new Date(s).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'—'}
function renderReturn(){ $('page').innerHTML=`<div class="panel"><h1>歸還物品</h1><form id="lookup"><fieldset ${ready?'':'disabled'}>${identity()}<button class="submit">查詢未歸還物品</button></fieldset></form><div id="loans"></div></div>`;$('lookup').onsubmit=e=>{e.preventDefault();action(e.submitter,async()=>{const credential=Object.fromEntries(new FormData(e.target));const rows=await api('lookup',credential);$('loans').innerHTML=rows.length?rows.map(x=>`<article class="card"><h2>${esc(x.itemName)}</h2><p>借出：${fmt(x.borrowedAt)}</p><p>預計歸還：${esc(x.dueDate)} · 未歸還 ${x.remaining} 件</p><form data-return="${esc(x.id)}"><label for="qty-${esc(x.id)}">本次歸還數量</label><input id="qty-${esc(x.id)}" name="quantity" type="number" min="1" max="${x.remaining}" step="1" value="${x.remaining}" required><button class="submit">確認歸還</button></form></article>`).join(''):'<div class="meta">沒有未歸還的物品。</div>';$('loans').querySelectorAll('form').forEach(f=>f.onsubmit=ev=>{ev.preventDefault();action(ev.submitter,async()=>{if(f.dataset.quantity!==f.elements.quantity.value){f.dataset.quantity=f.elements.quantity.value;f.dataset.requestId=crypto.randomUUID()}const result=await api('return',{...credential,loanId:f.dataset.return,quantity:f.elements.quantity.value,requestId:f.dataset.requestId});await loadItems().catch(()=>notice('歸還已完成，庫存更新稍後重試'));f.closest('.card').innerHTML=`<div class="success">已歸還 ${result.quantity} 件<br>${fmt(result.returnedAt)}${result.remaining?`<br>尚有 ${result.remaining} 件未歸還`:''}</div>`})})})}}
async function loadItems(){items=await api(user?'adminItems':'items')}
function navigate(p){page=p;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='borrow')renderBorrow();else if(p==='return')renderReturn();else renderAdmin()}
async function login(){if(!ready){notice('需先完成新系統 Firebase 設定');return}if(!sdk){const [a,b]=await Promise.all([import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js')]);sdk=b;auth=b.getAuth(a.initializeApp(portalFirebaseConfig,"inventoryPortalAuth"));}try{const result=await sdk.signInWithPopup(auth,new sdk.GoogleAuthProvider());user=result.user;await api('me');await loadItems();navigate('admin')}catch(e){user=null;notice(e.message)}}
async function renderAdmin(){if(!user){login();return}$('page').innerHTML=`<div class="admin-panel"><div class="tools"><button data-tab="stock">租借庫存</button><button data-tab="loans">借還紀錄</button><button data-tab="qr">學生借還 QR</button><button data-tab="promotion">文宣品庫存</button><button id="logout" class="quiet">登出</button></div><div id="adminContent"></div></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{adminTab=b.dataset.tab;renderAdminContent()});$('logout').onclick=async()=>{await sdk.signOut(auth);user=null;await loadItems();navigate('borrow')};await renderAdminContent()}
async function renderAdminContent(){const box=$('adminContent');if(adminTab==='promotion'){box.innerHTML='<h1>文宣品庫存</h1><p class="muted">文宣品的欄位及領用流程確認後，會在這裡加入。</p>';return}if(adminTab==='qr'){renderQR();return}if(adminTab==='loans'){await renderLoanList();return}await renderStock()}
async function renderStock(){const box=$('adminContent');box.innerHTML='<h1>租借庫存</h1><p>載入中…</p>';let settings;try{settings=await api('adminSettings')}catch(e){box.innerHTML=`<div class="banner">${esc(e.message)}。若剛更新網站，請先部署 Workers 1.1.0 程式。</div>`;return}
const options=settings.categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');
box.innerHTML=`<h1>租借庫存</h1><div class="stats"><div class="card">物品種類<strong>${items.length}</strong></div><div class="card">目前借出<strong>${items.reduce((n,x)=>n+x.borrowed,0)}</strong></div></div><div class="tools"><input id="search" placeholder="搜尋物品、編號、位置" aria-label="搜尋物品"><button id="export">匯出 Excel</button><button id="import">匯入 Excel</button></div><input id="file" type="file" accept=".xlsx,.xls,.csv" hidden><div id="importPreview"></div>
<details><summary>物品大類管理</summary><div class="category-tags">${settings.categories.map(c=>`<span>${esc(c)}</span>`).join('')||'<p class="muted">尚未建立物品大類。</p>'}</div><form id="newCategory">${field('categoryName','新增物品大類','text','maxlength="100"')}<button class="submit">建立大類</button></form></details>
<details open><summary>新增物品</summary><form id="newItem"><label>資產編號（自動產生）</label><div class="meta">${settings.nextId?`下一個編號：<strong>${esc(settings.nextId)}</strong>，儲存時自動配置。`:'編號已達 99999。'}${settings.canReset?'<button id="resetNumber" type="button" class="quiet">重設編號（測試用）</button>':''}</div>${field('itemName','物品名稱','text','maxlength="200"')}<label for="itemCategory">物品大類</label><select id="itemCategory" name="itemCategory" required><option value="">請選擇物品大類</option>${options}</select>${settings.categories.length?'':'<p class="muted">請先在「物品大類管理」建立大類。</p>'}${field('initial','庫存數量','number','min="0" step="1"')}<label for="location">存放位置</label><input id="location" name="location" maxlength="200"><label for="propertyId">財產編號（選填）</label><input id="propertyId" name="propertyId" maxlength="100"><button class="submit" ${!settings.nextId||!settings.categories.length?'disabled':''}>建立物品</button></form></details><div id="stockTable"></div>`;
const show=()=>{const q=$('search').value.trim().toLowerCase(),rows=items.filter(x=>[x.id,x.propertyId,x.name,x.category,x.location].join(' ').toLowerCase().includes(q));$('stockTable').innerHTML=table(['資產編號','物品名稱','物品大類','借出','可借','存放位置'],rows.map(x=>[x.id,x.name,x.category,x.borrowed,x.available,x.location]));const head=$('stockTable').querySelector('thead tr');head.insertAdjacentHTML('beforeend','<th>操作</th>');$('stockTable').querySelectorAll('tbody tr').forEach((tr,n)=>{const x=rows[n];tr.insertAdjacentHTML('beforeend',`<td><button class="danger" data-delete="${esc(x.id)}" ${x.borrowed>0?'disabled title="請先完成歸還"':''}>刪除</button></td>`)});$('stockTable').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const x=items.find(x=>x.id===b.dataset.delete);if(!confirm(`刪除「${x.name}」（${x.id}）？\n舊借還紀錄會保留，資產編號繼續累加。`))return;action(b,async()=>{await api('deleteItem',{id:x.id});await loadItems();await renderStock();notice('物品已刪除')})})};show();$('search').oninput=show;$('export').onclick=()=>xlsx(items.map(toExcel),'資產總表');$('import').onclick=()=>$('file').click();$('file').onchange=previewImport;
$('newCategory').onsubmit=e=>{e.preventDefault();action(e.submitter,async()=>{await api('category',{name:e.target.elements.categoryName.value});await renderStock();notice('物品大類已建立')})};
if($('resetNumber'))$('resetNumber').onclick=e=>{if(!confirm('測試用重設：從 00001 重新尋找未使用的編號。\n已使用的編號（含刪除的物品）會跳過，物品及借還紀錄都會保留。\n確定重設？'))return;action(e.target,async()=>{await api('resetNumber',{confirm:'RESET'});await renderStock();notice('編號已重設，會跳過已使用編號')})};
$('newItem').onsubmit=e=>{e.preventDefault();action(e.submitter,async()=>{const d=Object.fromEntries(new FormData(e.target)),data={name:d.itemName,category:d.itemCategory,total:Number(d.initial),location:d.location,propertyId:d.propertyId,note:''};const payload=JSON.stringify(data);if(e.target.dataset.payload!==payload){e.target.dataset.payload=payload;e.target.dataset.requestId=crypto.randomUUID()}data.requestId=e.target.dataset.requestId;const r=await api('item',data);await loadItems();await renderStock();notice('物品已建立，資產編號 '+r.id)})}}
async function renderLoanList(){const box=$('adminContent');box.innerHTML='<h1>借還紀錄</h1><p>載入中…</p>';try{const rows=(await api('loans')).map(x=>({...x,category:x.category||items.find(i=>i.id===x.itemId)?.category||'未分類'}));const opts=values=>[...new Set(values)].filter(Boolean).sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');box.innerHTML=`<h1>借還紀錄</h1><div class="filter-grid"><label>搜尋<input id="loanSearch" placeholder="姓名、學號、手機、物品或單號"></label><label>歸還狀態<select id="loanStatus"><option value="open">未歸還（含部分、逾期）</option><option value="all">全部紀錄</option><option value="partial">部分歸還</option><option value="returned">已歸還</option><option value="overdue">逾期未歸還</option></select></label><label>物品大類<select id="loanCategory"><option value="">全部大類</option>${opts(rows.map(x=>x.category))}</select></label><label>班級／單位<select id="loanUnit"><option value="">全部班級／單位</option>${opts(rows.map(x=>x.unit))}</select></label><label>身分<select id="loanIdentity"><option value="">全部身分</option><option value="student">學生</option><option value="staff">教職員／行政人員</option></select></label><label>借出日期起<input id="loanFrom" type="date"></label><label>借出日期迄<input id="loanTo" type="date"></label><label>每頁筆數<select id="loanSize"><option>25</option><option>50</option><option>100</option></select></label></div><div class="tools"><button id="exportLoans">匯出篩選結果</button><button id="clearFilters" class="quiet">清除篩選</button></div><p id="loanCount" class="muted"></p><div id="loanTable"></div><div class="pagination"><button id="prevPage" class="quiet">上一頁</button><span id="pageNumber"></span><button id="nextPage" class="quiet">下一頁</button></div>`;
let current=1,filtered=[];const show=()=>{const f={search:$('loanSearch').value,status:$('loanStatus').value,category:$('loanCategory').value,unit:$('loanUnit').value,identity:$('loanIdentity').value,from:$('loanFrom').value,to:$('loanTo').value};filtered=filterLoans(rows,f,taipeiDate());const size=Number($('loanSize').value),pages=Math.max(1,Math.ceil(filtered.length/size));current=Math.min(current,pages);$('loanCount').textContent=`共 ${rows.length} 筆，符合篩選 ${filtered.length} 筆`;$('loanTable').innerHTML=table(['資產編號／物品','借用人／學號','班級／單位','狀態','借出','預計歸還','未歸還','歸還紀錄'],filtered.slice((current-1)*size,current*size).map(x=>[`${x.itemId} ${x.itemName}`,`${x.name}／${x.studentId}`,x.unit,loanStatus(x,taipeiDate()),fmt(x.borrowedAt),x.dueDate,x.remaining,(x.returns||[]).map(r=>`${fmt(r.at)} ${r.quantity}件`).join('；')]));$('pageNumber').textContent=`${current} / ${pages} 頁`;$('prevPage').disabled=current===1;$('nextPage').disabled=current===pages};show();for(const id of ['loanSearch','loanStatus','loanCategory','loanUnit','loanIdentity','loanFrom','loanTo','loanSize'])$(id).oninput=()=>{current=1;show()};$('prevPage').onclick=()=>{current--;show()};$('nextPage').onclick=()=>{current++;show()};$('clearFilters').onclick=()=>{$('loanSearch').value='';$('loanStatus').value='all';for(const id of ['loanCategory','loanUnit','loanIdentity','loanFrom','loanTo'])$(id).value='';current=1;show()};$('exportLoans').onclick=()=>xlsx(filtered.map(x=>({'單號':x.id,'資產編號':x.itemId,'物品':x.itemName,'物品大類':x.category,'姓名':x.name,'學號/員編':x.studentId,'班級/單位':x.unit,'聯絡手機':x.phone,'狀態':loanStatus(x,taipeiDate()),'借出數量':x.quantity,'未歸還':x.remaining,'借出時間':fmt(x.borrowedAt),'預計歸還日期':x.dueDate,'歸還紀錄':(x.returns||[]).map(r=>`${fmt(r.at)} ${r.quantity}件`).join('；')})),'借還紀錄')}catch(e){box.textContent=e.message}}
function renderQR(){const base=new URL('./',location.href);base.search='';base.hash='';const urls=['borrow','return'].map(page=>{const u=new URL(base);u.searchParams.set('page',page);return u.href});$('adminContent').innerHTML=`<h1>學生借還 QR</h1><p class="muted">掃描後直接開啟手機借用或歸還頁面，學生不用登入帳號。</p><div class="qr-grid">${['借用物品','歸還物品'].map((name,i)=>`<article class="card qr-card"><h2>${name}</h2><canvas id="qr-${i}" aria-label="${name} QR"></canvas><p class="qr-url">${esc(urls[i])}</p><div class="tools"><button id="download-${i}">下載 QR 圖片</button><button id="copy-${i}" class="quiet">複製連結</button></div></article>`).join('')}</div>`;
try{urls.forEach((url,i)=>{const qr=window.qrcode(0,'M');qr.addData(url);qr.make();const canvas=$('qr-'+i),n=qr.getModuleCount(),scale=10,margin=4;canvas.width=canvas.height=(n+margin*2)*scale;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(qr.isDark(r,c))ctx.fillRect((c+margin)*scale,(r+margin)*scale,scale,scale);$('download-'+i).onclick=()=>{const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download=i?'歸還物品_QR.png':'借用物品_QR.png';a.click()};$('copy-'+i).onclick=async()=>{try{await navigator.clipboard.writeText(url);notice('連結已複製')}catch{notice('無法自動複製，請複製圖片下方網址')}}})}catch{$('adminContent').insertAdjacentHTML('beforeend','<p class="bad">QR 功能載入失敗，請重新整理。</p>')}}

function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length?'':'<p class="muted">沒有符合的紀錄。</p>'}</div>`}
function toExcel(x){return {'資產編號':x.id,'財產編號':x.propertyId,'物品大類':x.category,'物品名稱':x.name,'原始庫存數量':x.total,'目前借出數量':x.borrowed,'目前庫存數量':x.available,'庫存狀態':x.available>0?'在庫中':'無庫存','存放位置':x.location,'備註':x.note}}
function xlsx(rows,name){if(!window.XLSX){notice('Excel 功能載入失敗，請重新整理');return}const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(rows),name);XLSX.writeFile(w,name+'.xlsx')}
async function previewImport(e){try{if(!window.XLSX)throw Error('Excel 功能尚未載入');const file=e.target.files[0];if(!file)return;const w=XLSX.read(await file.arrayBuffer(),{type:'array'}),raw=XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:'',raw:false});pendingRows=raw.map(r=>({id:String(r['資產編號']).trim(),propertyId:r['財產編號'],category:r['物品大類'],name:r['物品名稱'],total:Number(r['原始庫存數量']),borrowed:Number(r['目前借出數量']),available:Number(r['目前庫存數量']),location:r['存放位置'],note:r['備註']}));const seen=new Set(),errors=[];pendingRows.forEach((r,i)=>{if(!r.id||!r.name||!r.category||['total','borrowed','available'].some(k=>!Number.isSafeInteger(r[k])||r[k]<0)||r.total!==r.borrowed+r.available||seen.has(r.id)||items.some(x=>x.id===r.id))errors.push(`第 ${i+2} 列 ${r.name||r.id}：資料異常、重複編號或已有物品`);seen.add(r.id)});$('importPreview').innerHTML=`<div class="meta">讀取 ${pendingRows.length} 筆。${errors.length?`<p class="bad">${errors.length} 筆需修正，尚未匯入。</p>${errors.slice(0,12).map(esc).join('<br>')}`:'僅新增物品，不覆蓋既有庫存。'}</div><button id="confirmImport" class="submit" ${errors.length?'disabled':''}>確認新增 ${pendingRows.length} 筆物品</button>`;$('confirmImport').onclick=e=>action(e.target,async()=>{for(let n=0;n<pendingRows.length;n+=100)await api('import',{items:pendingRows.slice(n,n+100)});await loadItems();await renderAdminContent();notice('匯入完成')})}catch(e){notice(e.message)}}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$('adminButton').onclick=()=>navigate('admin');
if(!ready)$('connection').innerHTML='<div class="banner">系統尚未完成資料庫設定，借還與管理功能暫未開放。</div>';else{try{await loadItems()}catch(e){$('connection').innerHTML=`<div class="banner">${esc(e.message)}</div>`}}navigate(new URLSearchParams(location.search).get('page')==='return'?'return':'borrow');

